name: Dromaius build

on: [push]

env:
    BUILD_TYPE: Release

jobs:
    build_native:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - uses: actions/checkout@v1
              with:
                submodules: true

            - name: Create build directory
              run: cmake -E make_directory ${{runner.workspace}}/_build

            - name: Run CMake
              shell: bash
              working-directory: ${{runner.workspace}}/_build
              run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

            - name: Build
              shell: bash
              working-directory: ${{runner.workspace}}/_build
              run: cmake --build . --config $BUILD_TYPE

            - name: Test
              shell: bash
              working-directory: ${{runner.workspace}}/build
              run: ctest -C $BUILD_TYPE

